# ── HTTP — app1 ───────────────────────────────────────────────────────────────
server {
    listen       80;
    server_name  app1.example.com;

    # Enable Service Discovery
    include svcDiscovery/svcDiscovery-collect.conf;

    location / {
        proxy_pass http://127.0.0.1:12345;
    }
}

# ── HTTP — app2 ───────────────────────────────────────────────────────────────
server {
    listen       80;
    server_name  app2.example.com;

    # Enable Service Discovery
    include svcDiscovery/svcDiscovery-collect.conf;

    location / {
        proxy_pass http://127.0.0.1:12345;
    }
}

# ── HTTPS — secure1 ──────────────────────────────────────────────────────────
server {
    listen       443 ssl;
    server_name  secure1.example.com;

    ssl_certificate      /etc/nginx/ssl/secure1.example.com.crt;
    ssl_certificate_key  /etc/nginx/ssl/secure1.example.com.key;
    ssl_protocols        TLSv1.2 TLSv1.3;
    ssl_ciphers          HIGH:!aNULL:!MD5;

    # Enable Service Discovery
    include svcDiscovery/svcDiscovery-collect.conf;

    location / {
        proxy_pass http://127.0.0.1:12345;
    }
}

# ── HTTPS — secure2 ──────────────────────────────────────────────────────────
server {
    listen       443 ssl;
    server_name  secure2.example.com;

    ssl_certificate      /etc/nginx/ssl/secure2.example.com.crt;
    ssl_certificate_key  /etc/nginx/ssl/secure2.example.com.key;
    ssl_protocols        TLSv1.2 TLSv1.3;
    ssl_ciphers          HIGH:!aNULL:!MD5;

    # Enable Service Discovery
    include svcDiscovery/svcDiscovery-collect.conf;

    location / {
        proxy_pass http://127.0.0.1:12345;
    }
}

# ── HTTP — dummy backend ───────────────────────────────────────────────────────────
server {
    listen 12345;

    location / {
        return 200 "Client IP: $remote_addr\nUser-Agent: $http_user_agent\n";
    }
}
