mirror              /svcDiscovery-mirror;
mirror_request_body off;

location = /svcDiscovery-mirror {
    internal;
    proxy_pass          http://svcDiscovery_collector;
    proxy_http_version  1.1;
    proxy_set_header    Connection              "";
    proxy_set_header    X-Consul-Server-Name    $consul_server_name;
    proxy_set_header    X-Consul-Server-Addr    $server_addr;
    proxy_set_header    X-Consul-Server-Port    $server_port;
    proxy_set_header    X-Consul-Server-Proto   $consul_proto;
}
