FROM nginx:stable-bookworm-perl@sha256:eebce3ed08062b82b5b643b3255d3e4046285d3b019ceed8b1fa5c3cc72a82c2

ARG NMS_URL
ARG NGINX_AGENT=false
ARG NGINX_AGENT_VERSION=2

# Initial packages setup
RUN apt-get -y update \
	&& apt-get -y install wget gpg \
	&& wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq \
	&& chmod +x /usr/bin/yq \
	&& set -x \
# Forward request logs to Docker log collector
	&& ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log \
# User and group
	&& groupadd -g 1001 nginx-agent \
	&& usermod root -G nginx-agent \
	&& usermod nginx -G nginx-agent \
# NGINX Agent
        && if [ "$NGINX_AGENT" = "true" ] ; then \
        apt-get -y install curl gnupg2 ca-certificates lsb-release debian-archive-keyring \
        && curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor > /usr/share/keyrings/nginx-archive-keyring.gpg \
        && echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://packages.nginx.org/nginx-agent/debian/ `lsb_release -cs` agent" > /etc/apt/sources.list.d/nginx-agent.list \
        && apt-get -y update \
        && apt-get -y install nginx-agent=`apt-cache madison nginx-agent | grep "| $NGINX_AGENT_VERSION\." | awk '{print $3}' | head -n1`; fi

# Startup script
COPY ./container/start.sh /deployment/
RUN chmod +x /deployment/start.sh && touch /.dockerenv

EXPOSE 80
STOPSIGNAL SIGTERM

CMD ["/deployment/start.sh"]
